name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      # Schritt 2: Deployment auf EC2
      - name: Deploy to EC2
        run: | 
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
        
          export NVM_DIR="/home/ubuntu/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use v16.15.0  # Die spezifische Node.js-Version laden (hier 16.15.0 als Beispiel)

          # Node.js und npm Version prüfen
          node -v
          npm -v

          # Installiere PM2 global
          npm install -g pm2
          
          # Lösche den alten Ordner, falls vorhanden, und lege einen neuen an
          rm -rf /home/ubuntu/react_pipeline
          mkdir -p /home/ubuntu/react_pipeline
          cd /home/ubuntu/react_pipeline
          
          # Klone das Repository von GitHub
          git clone https://github.com/${{ github.repository }}.git .

          # Installiere die npm-Abhängigkeiten
          npm install

          # Starte den Server mit PM2
          pm2 restart react-app || pm2 start npm --name "react-app" -- run start --watch

          # Stelle sicher, dass PM2 beim Neustart des Systems automatisch startet
          pm2 startup systemd
          pm2 save
          EOF
